In [17]:
import pickle
import sys
import getopt
import numpy as np
import scipy.io as io
import matplotlib
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d, Axes3D
from pdffuns import norm2D, knn2D


pfile='lab3.p'
with open(pfile, "rb") as fp:
     X=pickle.load(fp)
     
X


def plot_3d(P,X1,X2):
    fig = plt.figure()
    colors = ['r','b','c','g']
    ax = fig.gca(projection='3d')
    pmax = np.array([0.3]*(len(P)+1))
    for i,p in enumerate(P):
        clean_p = p.copy()
        clean_p[clean_p<p.max()/5000] = np.nan 
        ax.plot_surface(X1,X2,clean_p,color=colors[i])
        pmax[i] = p.max()
    
    ax.set(zlim=(0,pmax.max()*1.2), xlabel="x1", ylabel="x2", zlabel="p")
    
    plt.show()

In [10]:
X1 = X[0]
X2 = X[1]
my1 = X1.mean(axis=1).reshape(-1,1)
my2 = X2.mean(axis=1).reshape(-1,1)
Sgm1 = np.cov(X1)
Sgm2 = np.cov(X2)
n1 = X1.shape[1]
n2 = X2.shape[1]
print(X1)
print(X2)
print(my1)
print(my2)
print(Sgm1)
print(Sgm2)
print(n1)
print(n2)

[[2.8 2.  2.8 3. ]
 [4.8 5.8 6.9 5.8]]
[[ 1.7  2.9  3.8]
 [-2.6  0.2 -2.9]]
[[2.65 ]
 [5.825]]
[[ 2.8       ]
 [-1.76666667]]
[[0.19666667 0.005     ]
 [0.005      0.73583333]]
[[ 1.11       -0.01      ]
 [-0.01        2.92333333]]
4
3


In [18]:
Pw = [  n1/(n1+n2),
        n2/(n1+n2)]

x1 = np.arange(-9,11.2,0.1).reshape(-1,1)
x2 = np.arange(-9,11.2,0.1).reshape(-1,1)

p1,X11,X21 = norm2D(my1,Sgm1,x1,x2)
p2,X12,X22 = norm2D(my1,Sgm2,x1,x2)
# a) and b)
plot_3d([p1,p2],X11,X21)

<Figure size 640x480 with 0 Axes>

In [3]:
knn2D(0.5, 2, my1, X1)

0
2.8
0.1499999999999999
1
2.0
-0.6499999999999999
2
2.8
0.1499999999999999
3
3.0
0.3500000000000001
[1.0359174677550333, 0.6504805915628843, 1.0854146673046206, 0.3508917211904551]
[0.3508917211904551, 0.6504805915628843, 1.0359174677550333, 1.0854146673046206]
0.6504805915628843


0.37614166757316486

In [4]:
def labsol3(met='ML', discr='pxw', prm = []):
    # Initialise values:
    # - axes, x1 and x2

    # Load data from pickle files
    # - load into variable X, X[k], k = 0,...,M-1
    # - determine number of classes, M, from X
    # - determine feature dimension, l, from X[0]
    # Estimate prior probabilities, Pwi[k].
    # - iterate over classes, k = 0,...,M-1
    # - determine number of feature vectors, N[k]
    # - determine Pwi

    # Initialise method specific parameters
    # - on condition of met
    # - Maximum likelihood: my, Sgm (empty)
    # - Parzen window: h1 from prm
    # - kn nearest neighbor: knn from prm

    # - parameters, my[i] and Sgm[i], i = 0,...,M-1
    # - prior probabilities, Pw[i], i = 0,...,M-1
    # Determine class specific probability density functions, pxw[i], i = 0,...,M-1
    # - initialise pxw as empty list
    # - initialise total density function, p as zero
    # - iterate over classes, k = 0,...,M-1
    # - on condition of met: Maximum likelihood:
    # - estimate parameters my[k], Sgm[k]
    # - determine pxw[k] by using norm2D
    # - on condition of met: Parzen window:
    # - initialise pxw[k]
    # - determine hn
    # - iterate over samples in X[k], i = 1,...,N[k]
    # - let x be feature vector number i in X[k]
    # - use norm2D to determine pN
    # - update pxw[k] by adding pN
    # - update pxw by dividing by N[k]
    # - on condition of met: kn-nearest neighbor:
    # - use knn2D to determine pxw[k] from X[k]
    # - update p

    # Determine discriminant functions, g[k], k = 0,...,M-1
    
    # - initialise g as empty list
    # - iterate over classes, k = 0,...,M-1
    # - on condition of discr determine selected discriminant function
    # - Scaled pdfs
    # - Posterior probability
    # - pdfs (not really discriminant functions)

    # Plotting
    # - plot discriminant functions

SyntaxError: incomplete input (416649558.py, line 51)